# Generated by Django 3.0.3 on 2020-07-29 19:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cars_inventory', '0003_auto_20200723_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'نوع خودرو',
                'verbose_name_plural': 'انواع خودرو',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'موقعیت',
                'verbose_name_plural': 'موقعیت ها',
            },
        ),
        migrations.AddField(
            model_name='carsinventory',
            name='owner',
            field=models.CharField(max_length=150, null=True, verbose_name='مالک خودرو'),
        ),
        migrations.AddField(
            model_name='carsinventory',
            name='price',
            field=models.IntegerField(null=True, verbose_name='قیمت'),
        ),
        migrations.AddField(
            model_name='carsinventory',
            name='purchase_date',
            field=models.DateField(null=True, verbose_name='تاریخ خرید'),
        ),
        migrations.AddField(
            model_name='carsinventory',
            name='submit_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='زمان ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carsinventory',
            name='car_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars_inventory.CarType', verbose_name='نوع خودرو'),
        ),
        migrations.AddField(
            model_name='carsinventory',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars_inventory.Location', verbose_name='موقعیت'),
        ),
    ]
