# Generated by Django 3.0.3 on 2020-07-30 07:07

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_inventory', '0004_auto_20200729_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsinventory',
            name='purchase_date',
            field=django_jalali.db.models.jDateField(null=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
