# Generated by Django 3.0.3 on 2020-07-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_inventory', '0005_auto_20200730_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsinventory',
            name='purchase_date',
            field=models.DateField(null=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
