# Generated by Django 3.0.3 on 2020-07-30 09:56

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_inventory', '0006_auto_20200730_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsinventory',
            name='purchase_date',
            field=django_jalali.db.models.jDateField(null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='carsinventory',
            name='submit_date',
            field=django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
    ]
