# Generated by Django 3.0.8 on 2020-08-07 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_inventory', '0008_auto_20200730_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'وضعیت',
                'verbose_name_plural': 'وضعیت ها',
            },
        ),
        migrations.AddField(
            model_name='carsinventory',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars_inventory.StatusModel', verbose_name='وضعیت'),
        ),
    ]
