# Generated by Django 3.0.8 on 2020-08-07 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_inventory', '0009_auto_20200807_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsinventory',
            name='status',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars_inventory.StatusModel', verbose_name='وضعیت'),
        ),
    ]
