# Generated by Django 3.0.3 on 2020-08-02 19:00

from django.db import migrations, models
import payment.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='payment_image',
            field=models.ImageField(blank=True, null=True, upload_to=payment.models.upload_image_path, verbose_name='تصویر'),
        ),
    ]
