# Generated by Django 3.0.3 on 2020-07-31 11:22

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('cars_inventory', '0008_auto_20200730_1522'),
        ('customer_profile', '0001_initial'),
        ('cars_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeasingNameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'لیزینگ',
                'verbose_name_plural': 'لیزینگ ها',
            },
        ),
        migrations.CreateModel(
            name='SaleMethodModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'طرح فروش',
                'verbose_name_plural': 'طرح های فروش',
            },
        ),
        migrations.CreateModel(
            name='SaleContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationtime', models.DateTimeField(auto_now_add=True)),
                ('sale_price', models.IntegerField(verbose_name='قیمت فروش')),
                ('contractdate', django_jalali.db.models.jDateField(verbose_name='تاریخ قرارداد')),
                ('sell_type',
                 models.CharField(choices=[(1, 'نقد'), (2, 'اقساط')], max_length=10, verbose_name='نوع فروش')),
                ('period', models.IntegerField(verbose_name='مدت بازپرداخت')),
                ('loan_amount', models.IntegerField(verbose_name='مبلغ تسهیلات')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('chassisnum',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_inventory.CarsInventory',
                                   verbose_name='شماره شاسی')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                               to='customer_profile.CustomerModel', verbose_name='مشتری')),
                ('leasing_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                   to='sales_contract.LeasingNameModel', verbose_name='نام لیزینگ')),
                ('sale_expert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                  to='cars_account.UserProfileModel', verbose_name='کارشناس فروش')),
                ('sale_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                  to='sales_contract.SaleMethodModel', verbose_name='طرح فروش')),
            ],
            options={
                'verbose_name': 'قرارداد',
                'verbose_name_plural': 'قرارداد ها',
            },
        ),
    ]
