# Generated by Django 3.0.3 on 2020-08-01 17:16

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_contract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salemethodmodel',
            name='time',
            field=django_jalali.db.models.jDateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
