# Generated by Django 3.0.8 on 2020-08-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_contract', '0003_auto_20200801_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='salecontract',
            name='payment',
            field=models.BooleanField(default=False, verbose_name='تکمیل پرداخت'),
        ),
    ]
