# Generated by Django 3.0.3 on 2020-08-03 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positionsmodel',
            options={'verbose_name': 'سمت', 'verbose_name_plural': 'سمت ها'},
        ),
        migrations.AlterModelOptions(
            name='userprofilemodel',
            options={'verbose_name': 'پروفایل کاربر', 'verbose_name_plural': 'پروفایل های کربر'},
        ),
    ]
