# Generated by Django 3.0.8 on 2020-08-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_account', '0002_auto_20200803_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionsmodel',
            name='active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
    ]
