# Generated by Django 3.0.8 on 2020-08-08 14:43

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_account', '0006_auto_20200808_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='hireDate',
            field=django_jalali.db.models.jDateField(null=True, verbose_name='تاریخ استخدام'),
        ),
    ]
