# Generated by Django 3.0.8 on 2020-08-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_account', '0007_auto_20200808_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='buyacc',
            field=models.BooleanField(null=True, verbose_name='مجوز خرید'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='deliveracc',
            field=models.BooleanField(null=True, verbose_name='مجوز تحویل'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='sellacc',
            field=models.BooleanField(null=True, verbose_name='مجوز فروش'),
        ),
    ]
