# Generated by Django 3.0.8 on 2020-08-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_account', '0008_auto_20200808_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='roles',
            field=models.ManyToManyField(null=True, to='cars_account.Role'),
        ),
    ]
