# Generated by Django 3.0.8 on 2020-08-09 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars_account', '0009_auto_20200808_2252'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofilemodel',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='username',
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='roles',
            field=models.ManyToManyField(to='cars_account.Role'),
        ),
    ]
