# Generated by Django 3.0.8 on 2020-08-09 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_account', '0010_auto_20200809_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofilemodel',
            options={'verbose_name': 'پروفایل کاربر', 'verbose_name_plural': 'پروفایل های کاربر'},
        ),
    ]
