# Generated by Django 3.0.8 on 2020-08-09 12:54

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_account', '0012_auto_20200809_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='deliveracc',
            field=models.BooleanField(default=False, verbose_name='مجوز تحویل'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='fireDate',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ خروج'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='hireDate',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ استخدام'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='sellacc',
            field=models.BooleanField(default=False, verbose_name='مجوز فروش'),
        ),
    ]
