# Generated by Django 3.0.3 on 2020-08-03 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales_contract', '0003_auto_20200801_2150'),
        ('cars_account', '0002_auto_20200803_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDeliverModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=150)),
                ('deliver_status', models.CharField(choices=[(2, 'ناسالم'), (1, 'سالم')], max_length=150)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_contract.SaleContract')),
                ('deliver_expert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars_account.UserProfileModel')),
            ],
            options={
                'verbose_name': 'تحویل خودرو',
                'verbose_name_plural': 'تحویل خودروها',
            },
        ),
    ]
