# Generated by Django 3.0.8 on 2020-08-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_deliver', '0004_auto_20200807_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardelivermodel',
            name='deliver_status',
            field=models.CharField(choices=[(2, 'ناسالم'), (1, 'سالم')], max_length=150),
        ),
    ]
